### PR TITLE
Previously line clicking throws error because event was undefined

### PR DESCRIPTION
**Pull request by mrzygood**

### CODE REVIEW

**Comment by iamppz** [comment]
`window.event` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Window/event. 
Maybe we can find a different way to solve the bug, can you please tell me how to reproduce it?

**Comment by mrzygood** [comment]
> `window.event` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Window/event. Maybe we can find a different way to solve the bug, can you please tell me how to reproduce it?

Actually, I simply run application. When I click on any connection between nodes an error log occurs in console.
image

**Comment by iamppz** [comment]
My mistake, `event` is import from `d3`, not `window`: https://github.com/joyceworks/flowchart-vue/blob/6dc255f2af98a3489f52de0a0b65b0e4e596e483/src/components/flowchart/Flowchart.vue#L27

**Comment by iamppz** [comment]
Published 0.25.1 to NPM.

**Pull request merged**
