### PR TITLE
feat(events): add @selectconnection event

### PR DESCRIPTION
**Pull request by hrenly**
@selectconnection event added
@select and @selectconnection events fires before run render function

### CODE REVIEW

**Comment by hrenly** [comment]
Hello!
I want to propose to you add a selectConnections event, and make select events before run render function.
So, my question is, how can I build lib for MR? I tried `npm run build-lib` but this script doesn't make files, like in the `dist` folder.

**Comment by hrenly** [comment]
In my project I colorise blocks, who has connections with selected block, and if select event fired after render, I can't do it.

**Comment by iamppz** [comment]
> Hello!
> I want to propose to you add a selectConnections event, and make select events before run render function.
> So, my question is, how can I build lib for MR? I tried `npm run build-lib` but this script doesn't make files, like in the `dist` folder.

Hi, I tried `yarn build-lib` and it works well:

``` shell
⠹  Building for production as library (commonjs,umd,umd-min)...

...

Compiled successfully in 8434ms                              上午12:40:49

  File                         Size                   Gzipped

  dist/FlowChart.umd.min.js    172.07 KiB             53.87 KiB
  dist/FlowChart.umd.js        577.72 KiB             129.63 KiB
  dist/FlowChart.common.js     577.33 KiB             129.51 KiB
```

Can you show the output of `npm run build-lib` here?

**Comment by hrenly** [comment]
Thank you, for merge. Could you update npm package, if it possible? Or be better if I build lib and make another MR with lib files?

**Comment by iamppz** [comment]
Sorry for forget that, I'll publish it in the next hours

**Comment by hrenly** [comment]
Thanks a lot!

**Comment by hrenly** [comment]
Excuse me, but you promised me, that you update npm package. It's possible?

**Comment by iamppz** [comment]
[0.19.1](https://www.npmjs.com/package/flowchart-vue/v/0.19.1) published

**Pull request merged**
